songs2 = Song.create!( {name: "7 Days"} )
songs3 = Song.create!( {name: "Oldskool"} )
songs4 = Song.create!( {name: "Three little birds"} )
songs5 = Song.create!( {name: "Tennesse"} )
songs6 = Song.create!( {name: "Changes"} )
songs7 = Song.create!( {name: "Heroes"} )
songs8 = Song.create!( {name: "There's a Light That Never Goes Out"} )
